const TEMPLATES = {
    section: {
        width: 'standard',
        contentAlign: 'left',
        height: 'comfortable',
        spacing: 'medium',
        background: 'white',
        textTheme: 'dark',
    },
    row: {},
    column: {
        alignAcross: 'fill',
        alignDown: 'top',
    },
    eyebrow: {
        eyebrow: '',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    heading: {
        heading: '',
        headingEm: '',
        level: 'h2',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'rich-text': {
        body: '',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    image: {
        src: '',
        alt: '',
        caption: '',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    button: {
        label: '',
        href: '',
        action: '',
        arrow: true,
        variant: 'primary',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'steps-strip': {
        steps: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'avatar-row': {
        avatars: [],
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'rating-stars': {
        stars: '',
        ratingLabel: '',
        note: '',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'card-grid': {
        items: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'step-grid': {
        items: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    checklist: {
        checks: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'benefit-list': {
        items: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'trust-marks': {
        trustMarks: [],
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'stat-stamp': {
        value: '',
        text: '',
        align: 'left',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'quote-card': {
        quote: '',
        by: '',
        avatar: '',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    'info-card': {
        cardStyle: 'rating',
        title: '',
        value: '',
        note: '',
        spaceAbove: 'none',
        spaceBelow: 'none',
    },
    hero: {
        eyebrow: '',
        heading: '',
        headingEm: '',
        subhead: '',
        lead: '',
        ctas: [],
        avatars: [],
        rating: { stars: '', label: '', note: '' },
        image: { src: '', alt: '' },
        ratingCard: { label: '', note: '' },
        savingCard: { label: '', value: '', note: '' },
        steps: [],
    },
    'hero-full': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        image: { src: '', alt: '' },
        ctas: [],
    },
    'trust-cards': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        cta: { label: '', href: '', arrow: true },
        items: [],
    },
    'process-steps': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        items: [],
    },
    'why-list': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        items: [],
        image: { src: '', alt: '' },
        stamp: { value: '', text: '' },
    },
    'agent-compare': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        cta: { label: '', href: '', arrow: true },
        filters: [],
        sort: '',
        labels: {
            shortlist: 'Your shortlist',
            experience: 'Local experience',
            sales: 'Recent sales (12 mo)',
            commission: 'Commission estimate',
            marketing: 'Marketing budget',
            notes: 'Advisor notes',
            next: 'Next step',
        },
        agents: [],
    },
    family: {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        checks: [],
        ctas: [],
        image: { src: '', alt: '' },
        testimonial: { quote: '', by: '', avatar: '' },
    },
    cta: {
        eyebrow: '',
        heading: '',
        headingEm: '',
        body: '',
        background: 'navy',
        image: { src: '', alt: '' },
        buttons: [],
        trustMarks: [],
    },
    'text-image': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        body: '',
        imageSide: 'right',
        image: { src: '', alt: '' },
        cta: { label: '', href: '', arrow: true },
    },
    'stat-row': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        stats: [],
    },
    testimonials: {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        source: 'featured',
        chosen: '',
        limit: 3,
        layout: 'grid',
        items: [],
    },
    'faq-list': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        openFirst: true,
        items: [],
    },
    'team-intro': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        photoWidth: null,
        photoHeight: null,
        members: [],
    },
    'contact-form': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        intro: '',
        consent: '',
        submitLabel: 'Send enquiry',
        confirmation: '',
    },
    'blog-list': {
        eyebrow: '',
        heading: '',
        headingEm: '',
        lead: '',
        category: '',
        limit: 3,
        showMore: true,
        articles: [],
    },
};

export function defaultSectionData(type) {
    const template = TEMPLATES[type];

    return template ? JSON.parse(JSON.stringify(template)) : null;
}
